In [1]:
number = "1 2 3 4 5".split()
print(number)

['1', '2', '3', '4', '5']


In [2]:
int(number[1])

2

In [3]:
number_list_chars = "1 2 3 4 5".split()
print(number_list_chars)

['1', '2', '3', '4', '5']


In [4]:
number_list_int = [int(x) for x in number_list_chars] #list comphrehension
print(number_list_int)

[1, 2, 3, 4, 5]


In [5]:
for i in number_list_int:
    print(i)

1
2
3
4
5


In [6]:
for i in number_list_int:
    if i ==1:
        print("Bulbasaur")
    elif i == 2:
        print("Pikachu")
    elif i == 3:
        print("Charmender")  
    else:
        print("Invalid")

Bulbasaur
Pikachu
Charmender
Invalid
Invalid


In [4]:
#Dictionaries in python (hashmaps)

pokemon_map = {
    1 : "Bulbasaur",
    2 : "Pikachu",
    3 : "Charmender"
}

In [5]:
pokemon_map[3]

'Charmender'

In [9]:
pokemon_map[2]

'Pikachu'

In [9]:
if pokemon_map.get(5) is None:
    print("Pokemon Not Found")
else:
    print(pokemon_map[5])    

Pokemon Not Found


In [11]:
for i in number_list_int:
    if pokemon_map.get(i) is None:
        print("Pokemon Not Found")
    else:
        print(pokemon_map[i]) 

Bulbasaur
Pikachu
Charmender
Pokemon Not Found
Pokemon Not Found


In [7]:
pokemons = ["Bulbasaur", "Pikachu", "Charmender"]
pokemons[0]

'Bulbasaur'

In [13]:
pokemons1 = [("Bulbasaur", 200), ("Pikachu", 250), ("Charmender", 900, 200)]
pokemons1[2]

('Charmender', 900, 200)

In [14]:
pokemons1[0]

('Bulbasaur', 200)

In [15]:
print(type(pokemons1[0]))
print(type(pokemons1))

<class 'tuple'>
<class 'list'>


In [16]:
t = ("A", "B", "C") #Read only list

In [17]:
#Function
def printPokemons(number):

    #Dictonary
    pokemon_map = {
        1 : "Bulbasaur",
        2 : "Pikachu",
        3 : "Charmender"        
    }

    #Loop
    for i in number:
        if pokemon_map.get(i) is None:
            print("Pokemon Not Found")
        else:
            print(pokemon_map[i])
    return



In [18]:
number = [int(x) for x in input().split()]
printPokemons(number)

Pokemon Not Found
Bulbasaur
Bulbasaur
Pikachu
Charmender


### NUMPY

In [3]:
import numpy as np

In [20]:
# Few Important Functions

In [2]:
arr = np.array(1000000)

In [3]:
pythlist = list(range(100000))

In [10]:
%time for _ in range (10): [item*3 for item in pythlist]

Wall time: 90.7 ms


In [11]:
%time for _ in range(10): arr = arr*3

Wall time: 1.3 ms


<timed exec>:1: RuntimeWarning: overflow encountered in long_scalars


In [12]:
array = np.array([3, 2, 5, 4, 1])
print(array)
print(type(array))                         #ndarray = numpy dimesion array

[3 2 5 4 1]
<class 'numpy.ndarray'>


In [15]:
array1 = np.array([[3, 2, 5, 7, 0],[1, 12, 3, 4, 5]])
print(array1)

[[ 3  2  5  7  0]
 [ 1 12  3  4  5]]


In [25]:
array1.T

array([[ 3,  1],
       [ 2, 12],
       [ 5,  3],
       [ 7,  4],
       [ 0,  5]])

In [27]:
np.dot(array1,array1.T)

array([[ 87,  70],
       [ 70, 195]])

In [17]:
array1.shape


(2, 5)

In [18]:
array1.dtype

dtype('int32')

In [4]:
array2 = np.array([[3, 2, 0.5, 7, 0],[1, 12, 3, 4, 15]])
print(array2)

[[ 3.   2.   0.5  7.   0. ]
 [ 1.  12.   3.   4.  15. ]]


In [20]:
array2.shape

(2, 5)

In [21]:
array2.dtype

dtype('float64')

In [24]:
arr2 = np.array([[3, 2, 0.5, 5, 7],[1, 12, 3, 4, 5]], dtype = 'int32')
print(arr2)

[[ 3  2  0  5  7]
 [ 1 12  3  4  5]]


In [21]:
a = np.array([1, 2, 3, 4])

In [22]:
print(type(a))

<class 'numpy.ndarray'>


In [23]:
a.shape    #shape property tells what is the dimension of numpy

(4,)

In [25]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [26]:
print(b.shape)

(2, 4)


In [27]:
b.T     #T means Transpose

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [29]:
np.dot(b,b.T)     #dot product in numpy

array([[ 30,  70],
       [ 70, 174]])

In [31]:
np.random.randint(60, 100, 10)

array([94, 73, 78, 93, 75, 64, 88, 94, 95, 83])

In [33]:
np.random.randint(60, 100,(5,5))

array([[76, 95, 97, 63, 96],
       [80, 62, 85, 64, 70],
       [86, 79, 81, 60, 61],
       [71, 82, 83, 96, 96],
       [82, 97, 70, 85, 62]])

In [34]:
matrix = np.random.randint(60, 100, (5,5))

In [35]:
print(matrix)

[[76 61 86 67 61]
 [95 99 74 61 91]
 [67 91 94 83 73]
 [60 92 80 76 84]
 [91 68 81 72 96]]


In [36]:
np.max(matrix)  # max means maximum, the largest number of matrix

99

In [37]:
np.min(matrix)   #min means minimum, the smallest number

60

In [50]:
a = np.array([0,1,-2,3,4,6,6,6,6,6,7,-10,10,10,1])

In [49]:
np.argmin(a)  #argmin means index the where minimum element

7

In [51]:
np.unique(a)

array([-10,  -2,   0,   1,   3,   4,   6,   7,  10])

In [53]:
print(np.unique(a))

[-10  -2   0   1   3   4   6   7  10]


In [55]:
b = (np.unique(a,return_counts=True))

In [54]:
print(np.unique(a,return_counts=True))

(array([-10,  -2,   0,   1,   3,   4,   6,   7,  10]), array([1, 1, 1, 2, 1, 1, 5, 1, 2], dtype=int64))


In [56]:
print(b[0])

[-10  -2   0   1   3   4   6   7  10]


In [57]:
print(b[1])

[1 1 1 2 1 1 5 1 2]


In [28]:
np.zeros(4)

array([0., 0., 0., 0.])

In [30]:
np.zeros((4, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [31]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [32]:
np.ones(6).dtype

dtype('float64')

In [33]:
np.array((4, 6))

array([4, 6])

In [34]:
array1*array1

array([[  9,   4,  25,  49,   0],
       [  1, 144,   9,  16,  25]])

In [35]:
array1 + array1

array([[ 6,  4, 10, 14,  0],
       [ 2, 24,  6,  8, 10]])

In [36]:
array2 ** array2

array([[2.70000000e+01, 4.00000000e+00, 7.07106781e-01, 8.23543000e+05,
        1.00000000e+00],
       [1.00000000e+00, 8.91610045e+12, 2.70000000e+01, 2.56000000e+02,
        4.37893890e+17]])

In [38]:
np.array([12**12])

array([8916100448256], dtype=int64)

In [39]:
1/array1

C:\Users\DELL\AppData\Local\Temp/ipykernel_15072/2387133254.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/array1


array([[0.33333333, 0.5       , 0.2       , 0.14285714,        inf],
       [1.        , 0.08333333, 0.33333333, 0.25      , 0.2       ]])

In [5]:
array2

array([[ 3. ,  2. ,  0.5,  7. ,  0. ],
       [ 1. , 12. ,  3. ,  4. , 15. ]])

### Printing Arrays

In [5]:
a = np.arange(6)                                    # 1d array
print(a)

[0 1 2 3 4 5]


In [7]:
b = np.arange(12).reshape(4, 3)                       # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
c = np.arange(24).reshape(2, 3, 4)                      # 3d arrray 
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [9]:
print(np.arange(10000))          # if array is too long thne numpy automatically skips the centre part

[   0    1    2 ... 9997 9998 9999]


In [10]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


### Basic Operations