In [1]:
import numpy as np

In [8]:
array = ([3, 2, 5, 7, 7], [1, 12, 3, 4, 5])

In [9]:
array

([3, 2, 5, 7, 7], [1, 12, 3, 4, 5])

In [10]:
array[4:6]

()

In [11]:
array1 = np.array([5, 4, 64, 3, 3, 3])

In [12]:
array1[4:6]

array([3, 3])

In [13]:
arr = array1[4:6]

In [14]:
arr

array([3, 3])

In [15]:
arr[0] = 9

In [16]:
array1

array([ 5,  4, 64,  3,  9,  3])

In [19]:
array2 = np.array([5, 4, 64, 3, 3, 3])

In [20]:
arr1 = array2[4:6].copy()

In [21]:
arr1

array([3, 3])

In [22]:
arr1[0] = 9

In [23]:
array2

array([ 5,  4, 64,  3,  3,  3])

In [24]:
array1

array([ 5,  4, 64,  3,  9,  3])